const products = [
  {
    id: 'p1',
    name: 'Emerald Necklace',
    slug: 'emerald-necklace',
    category: 'Necklaces',
    price: 1999,
    material: 'Gold',
     rating: 4.8,
    image: '/images/emerald-necklace.jpg',
    description: 'An elegant emerald pendant with 24k gold chain.',
  },
  {
    id: 'p2',
    name: 'Diamond Ring',
    slug: 'diamond-ring',
    category: 'Rings',
    price: 2999,
    material: 'Gold',
    image: '/images/diamond-ring.jpg',
     rating: 4.8,
    description: 'A brilliant cut diamond set on white gold.',
  },
  {
    id: 'p3',
    name: 'Ruby Earrings',
    slug: 'ruby-earrings',
    category: 'Earrings',
    price: 1599,
    material: 'Gold',
    image: '/images/ruby-earrings.jpg',
     rating: 4.8,
    description: 'Vintage ruby studded earrings for a timeless look.',
  },
  {
    id: 'p4',
    name: 'Classic Gold Bangle',
    slug: 'classic-gold-bangle',
    category: 'Bangles',
    price: 1899,
    material: 'Gold',
    image: '/images/gold-bangle.jpg',
     rating: 4.8,
    description: '24k solid gold bangles in a traditional design.',
  },
  {
    id: 'p5',
    name: 'Sapphire Pendant',
    slug: 'sapphire-pendant',
    category: 'Necklaces',
    price: 2099,
    material: 'Gold',
    image: '/images/sapphire-pendant.jpg',
    rating: 4.8,
    description: 'Stunning sapphire pendant with diamond halo.',
  },
  {
    id: 'p6',
    name: 'Gold Necklace',
    slug: 'gold-necklace',
    category: 'Necklaces',
    price: 6999,
    material: 'Gold',
    image: '/images/necklace.jpg',
     rating: 4.8,
    description: 'Premium gold necklace for special occasions.',
  },
];

export default products;
